<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220613152118 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE wp_wc_download_log DROP FOREIGN KEY fk_wp_wc_download_log_permission_id');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('DROP TABLE wp_actionscheduler_actions');
        $this->addSql('DROP TABLE wp_actionscheduler_claims');
        $this->addSql('DROP TABLE wp_actionscheduler_groups');
        $this->addSql('DROP TABLE wp_actionscheduler_logs');
        $this->addSql('DROP TABLE wp_barcode_v3_dimension');
        $this->addSql('DROP TABLE wp_barcode_v3_fields_matching');
        $this->addSql('DROP TABLE wp_barcode_v3_label_sheets');
        $this->addSql('DROP TABLE wp_barcode_v3_paper_formats');
        $this->addSql('DROP TABLE wp_barcode_v3_profiles');
        $this->addSql('DROP TABLE wp_barcode_v3_template_to_user');
        $this->addSql('DROP TABLE wp_barcode_v3_templates');
        $this->addSql('DROP TABLE wp_barcode_v3_user_settings');
        $this->addSql('DROP TABLE wp_cd_customizations');
        $this->addSql('DROP TABLE wp_cocart_carts');
        $this->addSql('DROP TABLE wp_commentmeta');
        $this->addSql('DROP TABLE wp_comments');
        $this->addSql('DROP TABLE wp_links');
        $this->addSql('DROP TABLE wp_options');
        $this->addSql('DROP TABLE wp_postmeta');
        $this->addSql('DROP TABLE wp_posts');
        $this->addSql('DROP TABLE wp_term_relationships');
        $this->addSql('DROP TABLE wp_term_taxonomy');
        $this->addSql('DROP TABLE wp_termmeta');
        $this->addSql('DROP TABLE wp_terms');
        $this->addSql('DROP TABLE wp_usermeta');
        $this->addSql('DROP TABLE wp_users');
        $this->addSql('DROP TABLE wp_wc_admin_note_actions');
        $this->addSql('DROP TABLE wp_wc_admin_notes');
        $this->addSql('DROP TABLE wp_wc_category_lookup');
        $this->addSql('DROP TABLE wp_wc_customer_lookup');
        $this->addSql('DROP TABLE wp_wc_download_log');
        $this->addSql('DROP TABLE wp_wc_order_coupon_lookup');
        $this->addSql('DROP TABLE wp_wc_order_product_lookup');
        $this->addSql('DROP TABLE wp_wc_order_stats');
        $this->addSql('DROP TABLE wp_wc_order_tax_lookup');
        $this->addSql('DROP TABLE wp_wc_product_meta_lookup');
        $this->addSql('DROP TABLE wp_wc_reserved_stock');
        $this->addSql('DROP TABLE wp_wc_tax_rate_classes');
        $this->addSql('DROP TABLE wp_wc_webhooks');
        $this->addSql('DROP TABLE wp_woocommerce_api_keys');
        $this->addSql('DROP TABLE wp_woocommerce_attribute_taxonomies');
        $this->addSql('DROP TABLE wp_woocommerce_downloadable_product_permissions');
        $this->addSql('DROP TABLE wp_woocommerce_log');
        $this->addSql('DROP TABLE wp_woocommerce_order_itemmeta');
        $this->addSql('DROP TABLE wp_woocommerce_order_items');
        $this->addSql('DROP TABLE wp_woocommerce_payment_tokenmeta');
        $this->addSql('DROP TABLE wp_woocommerce_payment_tokens');
        $this->addSql('DROP TABLE wp_woocommerce_sessions');
        $this->addSql('DROP TABLE wp_woocommerce_shipping_zone_locations');
        $this->addSql('DROP TABLE wp_woocommerce_shipping_zone_methods');
        $this->addSql('DROP TABLE wp_woocommerce_shipping_zones');
        $this->addSql('DROP TABLE wp_woocommerce_tax_rate_locations');
        $this->addSql('DROP TABLE wp_woocommerce_tax_rates');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE wp_actionscheduler_actions (action_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, hook VARCHAR(191) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, status VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, scheduled_date_gmt DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, scheduled_date_local DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, args VARCHAR(191) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, schedule LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, group_id BIGINT UNSIGNED DEFAULT 0 NOT NULL, attempts INT DEFAULT 0 NOT NULL, last_attempt_gmt DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, last_attempt_local DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, claim_id BIGINT UNSIGNED DEFAULT 0 NOT NULL, extended_args VARCHAR(8000) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, INDEX status (status), INDEX args (args), INDEX last_attempt_gmt (last_attempt_gmt), INDEX hook (hook), INDEX scheduled_date_gmt (scheduled_date_gmt), INDEX group_id (group_id), INDEX claim_id (claim_id), PRIMARY KEY(action_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_actionscheduler_claims (claim_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, date_created_gmt DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, INDEX date_created_gmt (date_created_gmt), PRIMARY KEY(claim_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_actionscheduler_groups (group_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, slug VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, INDEX slug (slug(191)), PRIMARY KEY(group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_actionscheduler_logs (log_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, action_id BIGINT UNSIGNED NOT NULL, message TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, log_date_gmt DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, log_date_local DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, INDEX log_date_gmt (log_date_gmt), INDEX action_id (action_id), PRIMARY KEY(log_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_barcode_v3_dimension (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, label VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, is_default TINYINT(1) DEFAULT NULL, datetime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_barcode_v3_fields_matching (id INT UNSIGNED AUTO_INCREMENT NOT NULL, userId INT DEFAULT NULL, field VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, matching LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, datetime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_barcode_v3_label_sheets (id INT UNSIGNED AUTO_INCREMENT NOT NULL, userId INT DEFAULT NULL, name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, width NUMERIC(12, 4) DEFAULT NULL, height NUMERIC(12, 4) DEFAULT NULL, around NUMERIC(12, 4) DEFAULT NULL, across NUMERIC(12, 4) DEFAULT NULL, marginLeft NUMERIC(12, 4) DEFAULT NULL, marginRight NUMERIC(12, 4) DEFAULT NULL, marginTop NUMERIC(12, 4) DEFAULT NULL, marginBottom NUMERIC(12, 4) DEFAULT NULL, aroundCount INT DEFAULT NULL, acrossCount INT DEFAULT NULL, datetime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, paperId INT UNSIGNED DEFAULT 1 COMMENT \'linked to install\', `default` TINYINT(1) DEFAULT 0 NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_barcode_v3_paper_formats (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, width NUMERIC(12, 4) DEFAULT \'0.0000\', height NUMERIC(12, 4) DEFAULT \'0.0000\', `default` TINYINT(1) DEFAULT 0 NOT NULL, uol_id INT DEFAULT 1, landscape TINYINT(1) DEFAULT 0 NOT NULL, is_roll TINYINT(1) DEFAULT 0 NOT NULL, is_editable TINYINT(1) DEFAULT 1 NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_barcode_v3_profiles (id INT UNSIGNED AUTO_INCREMENT NOT NULL, userId INT DEFAULT NULL, name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, templateId INT DEFAULT NULL, paperId INT DEFAULT NULL, sheetId INT DEFAULT NULL, params LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, datetime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_barcode_v3_template_to_user (id INT UNSIGNED AUTO_INCREMENT NOT NULL, userId INT DEFAULT NULL, templateId INT DEFAULT NULL, datetime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_barcode_v3_templates (id INT UNSIGNED AUTO_INCREMENT NOT NULL, type VARCHAR(255) CHARACTER SET utf8 DEFAULT \'label\' COLLATE `utf8_general_ci`, name VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, slug VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, template TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, matching LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, matchingType VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, readonlyMatching TINYINT(1) DEFAULT 0 NOT NULL, is_default TINYINT(1) DEFAULT 0 NOT NULL, is_base TINYINT(1) DEFAULT 0 NOT NULL, height NUMERIC(12, 4) DEFAULT \'37.0000\', width NUMERIC(12, 4) DEFAULT \'70.0000\', uol_id INT DEFAULT 1, base_padding_uol NUMERIC(12, 4) DEFAULT NULL, code_match TINYINT(1) DEFAULT 0 NOT NULL, single_product_code TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, variable_product_code TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, fontStatus TINYINT(1) DEFAULT 1 NOT NULL, fontTagLink TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, fontCssRules TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, barcode_type VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, logo VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, senderAddress LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, datetime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_barcode_v3_user_settings (id INT UNSIGNED AUTO_INCREMENT NOT NULL, userId INT DEFAULT NULL, param VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, value TEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_general_ci`, datetime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_cd_customizations (role VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, menu LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, submenu LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, dashboard LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, UNIQUE INDEX role_2 (role), UNIQUE INDEX role (role), PRIMARY KEY(role)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_cocart_carts (cart_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, cart_key CHAR(42) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, cart_value LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, cart_expiry BIGINT UNSIGNED NOT NULL, UNIQUE INDEX cart_key (cart_key), PRIMARY KEY(cart_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_commentmeta (meta_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, comment_id BIGINT UNSIGNED DEFAULT 0 NOT NULL, meta_key VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, meta_value LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, INDEX meta_key (meta_key(191)), INDEX comment_id (comment_id), PRIMARY KEY(meta_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_comments (comment_ID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, comment_post_ID BIGINT UNSIGNED DEFAULT 0 NOT NULL, comment_author TINYTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, comment_author_email VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, comment_author_url VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, comment_author_IP VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, comment_date DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, comment_date_gmt DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, comment_content TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, comment_karma INT DEFAULT 0 NOT NULL, comment_approved VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'1\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, comment_agent VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, comment_type VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'comment\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, comment_parent BIGINT UNSIGNED DEFAULT 0 NOT NULL, user_id BIGINT UNSIGNED DEFAULT 0 NOT NULL, INDEX comment_date_gmt (comment_date_gmt), INDEX comment_author_email (comment_author_email(10)), INDEX comment_approved_date_gmt (comment_approved, comment_date_gmt), INDEX comment_parent (comment_parent), INDEX woo_idx_comment_type (comment_type), INDEX comment_post_ID (comment_post_ID), PRIMARY KEY(comment_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_links (link_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, link_url VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, link_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, link_image VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, link_target VARCHAR(25) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, link_description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, link_visible VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'Y\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, link_owner BIGINT UNSIGNED DEFAULT 1 NOT NULL, link_rating INT DEFAULT 0 NOT NULL, link_updated DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, link_rel VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, link_notes MEDIUMTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, link_rss VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, INDEX link_visible (link_visible), PRIMARY KEY(link_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_options (option_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, option_name VARCHAR(191) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, option_value LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, autoload VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'yes\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, INDEX autoload (autoload), UNIQUE INDEX option_name (option_name), PRIMARY KEY(option_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_postmeta (meta_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, post_id BIGINT UNSIGNED DEFAULT 0 NOT NULL, meta_key VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, meta_value LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, INDEX meta_key (meta_key(191)), INDEX post_id (post_id), PRIMARY KEY(meta_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_posts (ID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, post_author BIGINT UNSIGNED DEFAULT 0 NOT NULL, post_date DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, post_date_gmt DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, post_content LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, post_title TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, post_excerpt TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, post_status VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'publish\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, comment_status VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'open\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, ping_status VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'open\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, post_password VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, post_name VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, to_ping TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, pinged TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, post_modified DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, post_modified_gmt DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, post_content_filtered LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, post_parent BIGINT UNSIGNED DEFAULT 0 NOT NULL, guid VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, menu_order INT DEFAULT 0 NOT NULL, post_type VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'post\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, post_mime_type VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, comment_count BIGINT DEFAULT 0 NOT NULL, INDEX type_status_date (post_type, post_status, post_date, ID), INDEX post_parent (post_parent), INDEX post_name (post_name(191)), INDEX post_author (post_author), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_term_relationships (object_id BIGINT UNSIGNED DEFAULT 0 NOT NULL, term_taxonomy_id BIGINT UNSIGNED DEFAULT 0 NOT NULL, term_order INT DEFAULT 0 NOT NULL, INDEX term_taxonomy_id (term_taxonomy_id), PRIMARY KEY(object_id, term_taxonomy_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_term_taxonomy (term_taxonomy_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, term_id BIGINT UNSIGNED DEFAULT 0 NOT NULL, taxonomy VARCHAR(32) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, description LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, parent BIGINT UNSIGNED DEFAULT 0 NOT NULL, count BIGINT DEFAULT 0 NOT NULL, INDEX taxonomy (taxonomy), UNIQUE INDEX term_id_taxonomy (term_id, taxonomy), PRIMARY KEY(term_taxonomy_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_termmeta (meta_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, term_id BIGINT UNSIGNED DEFAULT 0 NOT NULL, meta_key VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, meta_value LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, INDEX meta_key (meta_key(191)), INDEX term_id (term_id), PRIMARY KEY(meta_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_terms (term_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, slug VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, term_group BIGINT DEFAULT 0 NOT NULL, INDEX name (name(191)), INDEX slug (slug(191)), PRIMARY KEY(term_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_usermeta (umeta_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, user_id BIGINT UNSIGNED DEFAULT 0 NOT NULL, meta_key VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, meta_value LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, INDEX meta_key (meta_key(191)), INDEX user_id (user_id), PRIMARY KEY(umeta_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_users (ID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, user_login VARCHAR(60) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, user_pass VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, user_nicename VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, user_email VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, user_url VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, user_registered DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, user_activation_key VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, user_status INT DEFAULT 0 NOT NULL, display_name VARCHAR(250) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, INDEX user_nicename (user_nicename), INDEX user_login_key (user_login), INDEX user_email (user_email), PRIMARY KEY(ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_wc_admin_note_actions (action_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, note_id BIGINT UNSIGNED NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, label VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, query LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, status VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, is_primary TINYINT(1) DEFAULT 0 NOT NULL, actioned_text VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, INDEX note_id (note_id), PRIMARY KEY(action_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_wc_admin_notes (note_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, type VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, locale VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, title LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, content LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, content_data LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, status VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, source VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, date_created DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, date_reminder DATETIME DEFAULT NULL, is_snoozable TINYINT(1) DEFAULT 0 NOT NULL, layout VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, image VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, is_deleted TINYINT(1) DEFAULT 0 NOT NULL, icon VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'info\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, PRIMARY KEY(note_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_wc_category_lookup (category_tree_id BIGINT UNSIGNED NOT NULL, category_id BIGINT UNSIGNED NOT NULL, PRIMARY KEY(category_tree_id, category_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_wc_customer_lookup (customer_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, user_id BIGINT UNSIGNED DEFAULT NULL, username VARCHAR(60) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, first_name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, last_name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, email VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, date_last_active DATETIME DEFAULT NULL, date_registered DATETIME DEFAULT NULL, country CHAR(2) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, postcode VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, city VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, state VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, INDEX email (email), UNIQUE INDEX user_id (user_id), PRIMARY KEY(customer_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_wc_download_log (download_log_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, permission_id BIGINT UNSIGNED NOT NULL, timestamp DATETIME NOT NULL, user_id BIGINT UNSIGNED DEFAULT NULL, user_ip_address VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'\' COLLATE `utf8mb4_unicode_520_ci`, INDEX timestamp (timestamp), INDEX permission_id (permission_id), PRIMARY KEY(download_log_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_wc_order_coupon_lookup (order_id BIGINT UNSIGNED NOT NULL, coupon_id BIGINT NOT NULL, date_created DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, discount_amount DOUBLE PRECISION DEFAULT \'0\' NOT NULL, INDEX coupon_id (coupon_id), INDEX date_created (date_created), PRIMARY KEY(order_id, coupon_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_wc_order_product_lookup (order_item_id BIGINT UNSIGNED NOT NULL, order_id BIGINT UNSIGNED NOT NULL, product_id BIGINT UNSIGNED NOT NULL, variation_id BIGINT UNSIGNED NOT NULL, customer_id BIGINT UNSIGNED DEFAULT NULL, date_created DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, product_qty INT NOT NULL, product_net_revenue DOUBLE PRECISION DEFAULT \'0\' NOT NULL, product_gross_revenue DOUBLE PRECISION DEFAULT \'0\' NOT NULL, coupon_amount DOUBLE PRECISION DEFAULT \'0\' NOT NULL, tax_amount DOUBLE PRECISION DEFAULT \'0\' NOT NULL, shipping_amount DOUBLE PRECISION DEFAULT \'0\' NOT NULL, shipping_tax_amount DOUBLE PRECISION DEFAULT \'0\' NOT NULL, INDEX date_created (date_created), INDEX product_id (product_id), INDEX customer_id (customer_id), INDEX order_id (order_id), PRIMARY KEY(order_item_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_wc_order_stats (order_id BIGINT UNSIGNED NOT NULL, parent_id BIGINT UNSIGNED DEFAULT 0 NOT NULL, date_created DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, date_created_gmt DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, num_items_sold INT DEFAULT 0 NOT NULL, total_sales DOUBLE PRECISION DEFAULT \'0\' NOT NULL, tax_total DOUBLE PRECISION DEFAULT \'0\' NOT NULL, shipping_total DOUBLE PRECISION DEFAULT \'0\' NOT NULL, net_total DOUBLE PRECISION DEFAULT \'0\' NOT NULL, returning_customer TINYINT(1) DEFAULT NULL, status VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, customer_id BIGINT UNSIGNED NOT NULL, INDEX customer_id (customer_id), INDEX date_created (date_created), INDEX status (status(191)), PRIMARY KEY(order_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_wc_order_tax_lookup (order_id BIGINT UNSIGNED NOT NULL, tax_rate_id BIGINT UNSIGNED NOT NULL, date_created DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, shipping_tax DOUBLE PRECISION DEFAULT \'0\' NOT NULL, order_tax DOUBLE PRECISION DEFAULT \'0\' NOT NULL, total_tax DOUBLE PRECISION DEFAULT \'0\' NOT NULL, INDEX tax_rate_id (tax_rate_id), INDEX date_created (date_created), PRIMARY KEY(order_id, tax_rate_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_wc_product_meta_lookup (product_id BIGINT NOT NULL, sku VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'\' COLLATE `utf8mb4_unicode_520_ci`, `virtual` TINYINT(1) DEFAULT 0, downloadable TINYINT(1) DEFAULT 0, min_price NUMERIC(19, 4) DEFAULT NULL, max_price NUMERIC(19, 4) DEFAULT NULL, onsale TINYINT(1) DEFAULT 0, stock_quantity DOUBLE PRECISION DEFAULT NULL, stock_status VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'instock\' COLLATE `utf8mb4_unicode_520_ci`, rating_count BIGINT DEFAULT 0, average_rating NUMERIC(3, 2) DEFAULT \'0.00\', total_sales BIGINT DEFAULT 0, tax_status VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'taxable\' COLLATE `utf8mb4_unicode_520_ci`, tax_class VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'\' COLLATE `utf8mb4_unicode_520_ci`, INDEX downloadable (downloadable), INDEX stock_quantity (stock_quantity), INDEX min_max_price (min_price, max_price), INDEX `virtual` (`virtual`), INDEX stock_status (stock_status), INDEX onsale (onsale), PRIMARY KEY(product_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_wc_reserved_stock (order_id BIGINT NOT NULL, product_id BIGINT NOT NULL, stock_quantity DOUBLE PRECISION DEFAULT \'0\' NOT NULL, timestamp DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, expires DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, PRIMARY KEY(order_id, product_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_wc_tax_rate_classes (tax_rate_class_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, slug VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, UNIQUE INDEX slug (slug(191)), PRIMARY KEY(tax_rate_class_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_wc_webhooks (webhook_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, status VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, name TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, user_id BIGINT UNSIGNED NOT NULL, delivery_url TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, secret TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, topic VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, date_created DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, date_created_gmt DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, date_modified DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, date_modified_gmt DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, api_version SMALLINT NOT NULL, failure_count SMALLINT DEFAULT 0 NOT NULL, pending_delivery TINYINT(1) DEFAULT 0 NOT NULL, INDEX user_id (user_id), PRIMARY KEY(webhook_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_woocommerce_api_keys (key_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, user_id BIGINT UNSIGNED NOT NULL, description VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, permissions VARCHAR(10) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, consumer_key CHAR(64) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, consumer_secret CHAR(43) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, nonces LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, truncated_key CHAR(7) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, last_access DATETIME DEFAULT NULL, INDEX consumer_secret (consumer_secret), INDEX consumer_key (consumer_key), PRIMARY KEY(key_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_woocommerce_attribute_taxonomies (attribute_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, attribute_name VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, attribute_label VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, attribute_type VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, attribute_orderby VARCHAR(20) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, attribute_public INT DEFAULT 1 NOT NULL, INDEX attribute_name (attribute_name(20)), PRIMARY KEY(attribute_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_woocommerce_downloadable_product_permissions (permission_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, download_id VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, product_id BIGINT UNSIGNED NOT NULL, order_id BIGINT UNSIGNED DEFAULT 0 NOT NULL, order_key VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, user_email VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, user_id BIGINT UNSIGNED DEFAULT NULL, downloads_remaining VARCHAR(9) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, access_granted DATETIME DEFAULT \'0000-00-00 00:00:00\' NOT NULL, access_expires DATETIME DEFAULT NULL, download_count BIGINT UNSIGNED DEFAULT 0 NOT NULL, INDEX order_id (order_id), INDEX download_order_product (download_id, order_id, product_id), INDEX user_order_remaining_expires (user_id, order_id, downloads_remaining, access_expires), INDEX download_order_key_product (product_id, order_id, order_key(16), download_id), PRIMARY KEY(permission_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_woocommerce_log (log_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, timestamp DATETIME NOT NULL, level SMALLINT NOT NULL, source VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, message LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, context LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, INDEX level (level), PRIMARY KEY(log_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_woocommerce_order_itemmeta (meta_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, order_item_id BIGINT UNSIGNED NOT NULL, meta_key VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, meta_value LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, INDEX meta_key (meta_key(32)), INDEX order_item_id (order_item_id), PRIMARY KEY(meta_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_woocommerce_order_items (order_item_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, order_item_name TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, order_item_type VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, order_id BIGINT UNSIGNED NOT NULL, INDEX order_id (order_id), PRIMARY KEY(order_item_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_woocommerce_payment_tokenmeta (meta_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, payment_token_id BIGINT UNSIGNED NOT NULL, meta_key VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, meta_value LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_520_ci`, INDEX meta_key (meta_key(32)), INDEX payment_token_id (payment_token_id), PRIMARY KEY(meta_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_woocommerce_payment_tokens (token_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, gateway_id VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, token TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, user_id BIGINT UNSIGNED DEFAULT 0 NOT NULL, type VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, is_default TINYINT(1) DEFAULT 0 NOT NULL, INDEX user_id (user_id), PRIMARY KEY(token_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_woocommerce_sessions (session_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, session_key CHAR(32) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, session_value LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, session_expiry BIGINT UNSIGNED NOT NULL, UNIQUE INDEX session_key (session_key), PRIMARY KEY(session_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_woocommerce_shipping_zone_locations (location_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, zone_id BIGINT UNSIGNED NOT NULL, location_code VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, location_type VARCHAR(40) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, INDEX location_type_code (location_type(10), location_code(20)), INDEX location_id (location_id), PRIMARY KEY(location_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_woocommerce_shipping_zone_methods (instance_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, zone_id BIGINT UNSIGNED NOT NULL, method_id VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, method_order BIGINT UNSIGNED NOT NULL, is_enabled TINYINT(1) DEFAULT 1 NOT NULL, PRIMARY KEY(instance_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_woocommerce_shipping_zones (zone_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, zone_name VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, zone_order BIGINT UNSIGNED NOT NULL, PRIMARY KEY(zone_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_woocommerce_tax_rate_locations (location_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, location_code VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, tax_rate_id BIGINT UNSIGNED NOT NULL, location_type VARCHAR(40) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_520_ci`, INDEX location_type_code (location_type(10), location_code(20)), INDEX tax_rate_id (tax_rate_id), PRIMARY KEY(location_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE wp_woocommerce_tax_rates (tax_rate_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, tax_rate_country VARCHAR(2) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, tax_rate_state VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, tax_rate VARCHAR(8) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, tax_rate_name VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, tax_rate_priority BIGINT UNSIGNED NOT NULL, tax_rate_compound INT DEFAULT 0 NOT NULL, tax_rate_shipping INT DEFAULT 1 NOT NULL, tax_rate_order BIGINT UNSIGNED NOT NULL, tax_rate_class VARCHAR(200) CHARACTER SET utf8mb4 DEFAULT \'\' NOT NULL COLLATE `utf8mb4_unicode_520_ci`, INDEX tax_rate_priority (tax_rate_priority), INDEX tax_rate_state (tax_rate_state(2)), INDEX tax_rate_class (tax_rate_class(10)), INDEX tax_rate_country (tax_rate_country), PRIMARY KEY(tax_rate_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE wp_wc_download_log ADD CONSTRAINT fk_wp_wc_download_log_permission_id FOREIGN KEY (permission_id) REFERENCES wp_woocommerce_downloadable_product_permissions (permission_id) ON DELETE CASCADE');
        $this->addSql('DROP TABLE user');
    }
}
